root-key = "Value"
array-of-inline = [
	{ trout = true },
	{ salmon = false }
]

inline-table = { fish = "trout", to-usurp = "MD_5" }

array-of-arrays = [ [ "a" ], [ "b" ], [ [ "c" ] ] ]

[table]
table-key = 10
longer-table-key = 1000

[table.subtable]
subtable-key = true
really-really-obnoxiously-long-key = -nan

[instants]
odt = 2025-01-05T12:00:00.0000-07:00
ldt = 2025-01-06T04:30:00.50
ld = 2025-01-07
lt = 14:30:00.9999

[[array-of-tables]]
trout = true 

[[array-of-tables]]
salmon = false

[[array-of-tables.subtable]]
something = "what"
